// <auto-generated />
namespace ISG.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IsgToplu_IsgEgitimiEsle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsgToplu_IsgEgitimiEsle));
        
        string IMigrationMetadata.Id
        {
            get { return "202203181755592_IsgToplu_IsgEgitimiEsle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
