// <auto-generated />
namespace ISG.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ISG_TopluEgitimSablonlari2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ISG_TopluEgitimSablonlari2));
        
        string IMigrationMetadata.Id
        {
            get { return "202203021143204_ISG_TopluEgitimSablonlari2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
