// <auto-generated />
namespace ISG.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ISG_TopluEgitimSablonlari : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ISG_TopluEgitimSablonlari));
        
        string IMigrationMetadata.Id
        {
            get { return "202203021135328_ISG_TopluEgitimSablonlari"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
