// <auto-generated />
namespace ISG.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class calisma_analizi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(calisma_analizi));
        
        string IMigrationMetadata.Id
        {
            get { return "202201291110365_calisma_analizi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
