// <auto-generated />
namespace ISG.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IsgEgitimleriEgitim_Turu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsgEgitimleriEgitim_Turu));
        
        string IMigrationMetadata.Id
        {
            get { return "202206170958377_IsgEgitimleriEgitim_Turu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
