// <auto-generated />
namespace ISG.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SirketDetayi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SirketDetayi));
        
        string IMigrationMetadata.Id
        {
            get { return "202202210820136_SirketDetayi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
